# Generated by Django 4.2.4 on 2024-04-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=14, unique=True)),
                ('vehicle', models.CharField(max_length=20)),
                ('parking_slot', models.IntegerField()),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
