# Generated by Django 4.2.4 on 2024-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0003_alter_transaction_parking_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='lp_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
